# Generated by Django 3.2.8 on 2021-10-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=20)),
                ('status_desc', models.CharField(max_length=40)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'CustomerStatus',
                'db_table': 'CustomerStatus',
            },
        ),
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=20)),
                ('status_desc', models.CharField(max_length=40)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'ProductStatus',
                'db_table': 'ProductStatus',
            },
        ),
        migrations.CreateModel(
            name='RewardStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=20)),
                ('status_desc', models.CharField(max_length=40)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'RewardStatus',
                'db_table': 'RewardStatus',
            },
        ),
        migrations.CreateModel(
            name='StoreStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=20)),
                ('status_desc', models.CharField(max_length=40)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'StoreStatus',
                'db_table': 'StoreStatus',
            },
        ),
    ]
