# Generated by Django 3.2.8 on 2021-10-08 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0002_customerstatus_productstatus_rewardstatus_storestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=20)),
                ('label_desc', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Customer Label',
                'db_table': 'Customer Label',
            },
        ),
        migrations.CreateModel(
            name='EmployeeLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=20)),
                ('label_desc', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Employee Label',
                'db_table': 'Employee Label',
            },
        ),
        migrations.AlterModelOptions(
            name='customerstatus',
            options={'verbose_name_plural': 'Customer Status'},
        ),
        migrations.AlterModelOptions(
            name='employeestatus',
            options={'verbose_name_plural': 'Employee Status'},
        ),
        migrations.AlterModelOptions(
            name='productstatus',
            options={'verbose_name_plural': 'Product Status'},
        ),
        migrations.AlterModelOptions(
            name='rewardstatus',
            options={'verbose_name_plural': 'Reward Status'},
        ),
        migrations.AlterModelOptions(
            name='storestatus',
            options={'verbose_name_plural': 'Store Status'},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='begin_date',
            new_name='created_date',
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=14)),
                ('comments', models.TextField(blank=True, null=True)),
                ('birthdate', models.DateField()),
                ('created_date', models.DateField()),
                ('create_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bakery.employee')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bakery.location')),
            ],
            options={
                'verbose_name_plural': 'Loyalty Customer',
                'db_table': 'Customer',
            },
        ),
    ]
